language: php

php:
  - hhvm
  - 5.3
  - 5.4
  - 5.5
  - 5.6

matrix:
    allow_failures:
        - php: 5.6

before_script:
  - composer self-update
  - composer install --dev --prefer-source --no-interaction

script:
  - ./tests/server.php &
  - php vendor/bin/phpunit --coverage-text --coverage-clover coverage.clover -v
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;'
